services:
  v3-external-api-docs:
    image: rjyspl/v3-external-api-docs:latest
    container_name: v3-external-api-docs

    # Load environment variables from the .env file
    env_file:
      - .env

    ports:
      - '127.0.0.1:8682:3000'

    restart: always
